---
# GC5 N96 ORCA1 spinup analysis
name: ukesm_bgcval_alkalinity

# Run the single job analysis
do_analysis_timeseries: True 
# Download from mass:
do_mass_download: False

# master analysis suite
master_suites: kmf bgc alkalinity physics

clean: True

# Job ID's suites as named by Rose/Cylc
# •     u-co094 - no alk added
# •     u-cp800 - alk add at surface
# •     u-cp799 - alk added at bathy - or 100m (if bathy deeper)
# •     u-cn857 - alk added at bathy - or 200m (if bathy deeper)
#
jobs:
#    u-co094:
#        description: 'no alk added'
#        colour: purple
#        thickness: 0.7
#        linestyle: '-'
#        shifttime: 0.
#        suite: bgc #alkalinity
    u-cp800:
       description: 'alk add at surface'
       colour: blue 
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: bgc #alkalinity
#
    u-cp799:
       description: 'alk added at bathy - or 100m (if bathy deeper)'
       colour: green
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: kmf bgc alkalinity physics

#    u-cp857:
#       description: 'alk added at bathy - or 200m (if bathy deeper)'
#       colour: green
#       thickness: 0.7
#       linestyle: '-'
#       shifttime: 0.
#       suite: bgc #alkalinity




